# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "13fbcbd7273559d104f90934b0b403b2"
application_url = "https://trinidad-fate-filing-christ.trycloudflare.com"
embedded = true
name = "remix-chat"
handle = "remix-chat-193"

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,read_products,write_discounts,write_products,write_customers"

[auth]
redirect_urls = [
  "https://trinidad-fate-filing-christ.trycloudflare.com/auth/callback",
  "https://trinidad-fate-filing-christ.trycloudflare.com/auth/shopify/callback",
  "https://trinidad-fate-filing-christ.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true
