# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "13fbcbd7273559d104f90934b0b403b2"
application_url = "https://included-tampa-reservations-bride.trycloudflare.com"
embedded = true
name = "remix-chat"
handle = "remix-chat-193"

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,read_products,write_customers,write_discounts,write_products"

[auth]
redirect_urls = [
  "https://included-tampa-reservations-bride.trycloudflare.com/auth/callback",
  "https://included-tampa-reservations-bride.trycloudflare.com/auth/shopify/callback",
  "https://included-tampa-reservations-bride.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
