# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "bf9c1f00221e683d230a1673e3c7efd7"
application_url = "https://example.com/"
embedded = true
name = "remix-chat"
handle = "remix-chat-159"

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,read_inventory,write_discounts"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[pos]
embedded = false
