# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8023ccb5bde0e960e5dd40875a7efaca"
application_url = "https://kelkoo-trackback-kids-strategy.trycloudflare.com"
embedded = true
name = "remix-chat"
handle = "remix-chat-193"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://kelkoo-trackback-kids-strategy.trycloudflare.com/auth/callback",
  "https://kelkoo-trackback-kids-strategy.trycloudflare.com/auth/shopify/callback",
  "https://kelkoo-trackback-kids-strategy.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
